---
version: "3.6"
services:
  smokeping:
    image: linuxserver/smokeping
    container_name: smokeping
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /home/vincent/docker/smokeping/config:/config
      - /home/vincent/docker/smokeping/data:/data
    networks:
      pub_net:
        ipv4_address: 192.168.0.150
    restart: unless-stopped
networks:
  pub_net:
    external: true
